### ISSUE TITLE
feature request: add grade accuracy to results

### ISSUE THREAD

**Issue by yuderekyu** [lemeryfertitta/Climbdex#15]
curious how you'd feel if we added the grade accuracy of a climb in the results list? it feels a lil confusing if someone filters by grade accuracy, but that value isn't shown to a user in  the results 🤔 

that's exposed via the `quality` property in the api, right? would love to contribute if possible

**Comment by lemeryfertitta** [comment]
I think that would be a nice addition. I think it would be even more useful if the `difficulty_average` was just displayed directly, which is what the database field that the grade accuracy is based off of. One problem I'd be a little worried about is general noise and readability of the list, especially on mobile. In the database, the `difficulty_average` is a number like `22.01234` which corresponds to something like `V6.01234`. I think this would be a little confusing to look at, given that we aren't use to decimals in climbing grades. We could add another value next to the rating, but it seems like it could get wordy. Do you have an idea for how we could represent this nicely?

`quality` is the star rating.

**Comment by yuderekyu** [comment]
perhaps we make it an opt in feature? we could display a "show grade average" toggle at the top of the search results to control whether the average grade is displayed per result. the toggle could default to off. 

if it's on, i could see us either being specific, like displaying `Grade average: V6.0023` per result, or display that value next to some sort of icon [[src](https://thenounproject.com/icon/difficulty-3899028/)] to reduce real estate. this would only apply to desktop, but we could go further and add a `title` element witihin the icon to displays `Grade average` if a user hovers over it and also add the icon to the initial filter search section to better associate the two things.

curious what you think of either of these ideas!

**Comment by lemeryfertitta** [comment]
I like the idea of toggling. Maybe just 
<img width="309" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/6968022/86b58c12-fccc-42f3-b4b5-542a78d82699">

Where the parentheses value is the +/- over the grade. The toggle could be somewhere below the back link in the result header:

<img width="358" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/6968022/c5011e16-90e6-4b25-b273-079769f2f3b7">

**Comment by lemeryfertitta** [comment]
This has been implemented and deployed. I opted to go without the toggle, it seemed clear enough and I felt like toggling may have been more of a source of confusion/hassle then necessary.

Feel free to reopen/create a new issue if you run into any problems with it! Thanks for the idea.
