### ISSUE TITLE
feature request: add left right button to 

### ISSUE THREAD

**Issue by gardaholm** [lemeryfertitta/Climbdex#16]
really awesome repo, love it!

For the mobile view a left right button, next to the Climbs name would be really handy. 
So you can scroll through the route-images easier. 

<img width="438" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/48827ef4-e7d1-4075-878b-cff165a463e7">

**Comment by lemeryfertitta** [comment]
Great idea! I'll work on this in the next few days unless you're interested, in which case I am happy to accept PRs.

**Comment by gardaholm** [comment]
would be great if you have time. left/right buttons would be really nice addition.

I played around a bit with another feature I had in mind: adding a username, fetching the ticked climbs and hiding them from the list. but I'm still having troubles with the api and can't fetch my own logbook :)

**Comment by lemeryfertitta** [comment]
@gardaholm prev/next buttons deployed! Check it out and let me know what you think. I think left/right swipe would be a nice addition, I'll branch that out to a separate issue.

>  adding a username, fetching the ticked climbs and hiding them from the list

You would need to add a password as well, getting the ticked climbs requires a login. There are two ways to do it - you can use the sync function, or the logbook API. Both should work. If we wanted to avoid storing user data (more expensive/complex), the logbook API would be the way to go.  I think this is a much bigger ask though, as there would need to be some convenient way to "log in," and you'd have to log in separately for each type of board.

This kind of request points to a much bigger idea, which is just to fully replace these apps with an open source board app that can do everything for every board. I think thats a little ambitious for Climbdex at this point, but its something I've certainly thought about and do have some interest in working on.

**Comment by gardaholm** [comment]
nice addition, this is really excellent to go through the results. love it

**Comment by gardaholm** [comment]
nice addition, this is really excellent to go through the results. love it
