### ISSUE TITLE
Feature request: metrics 

### ISSUE THREAD

**Issue by stuartsummers** [lemeryfertitta/Climbdex#18]
So I know the individual apps have their own way of tracking climbs over time. I really like the idea of open sourcing some of that, both to consolidate the data in one place and to allow for more refined training progression. Is this planned?

I'd like to spend some time here when I can, but right now can't commit too much. I'm more proficient in C and Python, but some older experience with various OOP languages. Also interested in learning some of the others here of course.

**Comment by lemeryfertitta** [comment]
Feel free to correct me if I'm misinterpreting your request, but you can already aggregate all of your logbook data using the underlying Python library that helps to power Climbdex. If you haven't already, check out [Boardlib](https://github.com/lemeryfertitta/BoardLib). Specifically, the `boardlib logbook` command sounds like what you are looking for. You can use this command to download all of your logbook entries to a CSV, then do whatever analysis/data representation you'd like on that CSV.

**Comment by stuartsummers** [comment]
Oh excellent! I'll take a closer look. I guess the feature request here is essentially just an ask to both integrate and provide a framework to start adding features to present that data in a meaningful way. Feel free to close this one if it makes sense. I'll think a little more specifics and get back.

**Comment by lemeryfertitta** [comment]
>  the feature request here is essentially just an ask to both integrate and provide a framework to start adding features to present that data in a meaningful way.

Makes sense! I would definitely be interested in that. I don't quite have a vision for what that might look like, so please do share if you have some ideas! I'll close this for now since there is nothing immediately actionable, but feel free to reopen or create new issues in the future.
