### ISSUE TITLE
Additional navigation options for climbs and beta videos

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#19]
Branching from #16 - it would be nice to be able to get the previous/next climb or beta video in the list using left/right swipes on mobile, respectively. Additionally, on desktop it would be nice to use the left/right arrow keys for this purpose.

This should be pretty straightforward, using something like [this](https://stackoverflow.com/questions/2264072/detect-a-finger-swipe-through-javascript-on-the-iphone-and-android) code to detect the left/right swipes on the climb or beta div, then behaving similarly to the prev/next buttons.

**Comment by Kehinde13** [comment]
I would like to work on this

**Comment by lemeryfertitta** [comment]
> I would like to work on this

Sure! I'll assign to you. I haven't put in any instructions in the README yet for local development. I'll try to get to that today. Feel free to reach out if you have any questions.

**Comment by Kehinde13** [comment]
Alright, I would appreciate if you can add instructions on local development to the README

**Comment by lemeryfertitta** [comment]
Instructions added. Let me know if you run into any issues and I can help troubleshoot/improve the instructions.

**Comment by lemeryfertitta** [comment]
Increased the scope on this one to include left/right arrow keys and also include the beta page, which behaves very similarly to the results page.

I am going to remove the assignment on this one to free it up for other contributors as @Kehinde13 does not appear to be working on it.

**Comment by lemeryfertitta** [comment]
Deployed
