### ISSUE TITLE
Includes mirror problems when searching with selected holds

### ISSUE THREAD

**Issue by Theruz** [lemeryfertitta/Climbdex#21]
Some board have a mirror layout. 
When searching for problems with a selection of holds, it would be convenient that the search results also includes mirrored problems

for example, searching with these holds
<img width="300" alt="Screenshot 2024-01-30 at 13 58 53" src="https://github.com/lemeryfertitta/Climbdex/assets/4202355/d88c3a32-7aa8-413d-a50e-2f8a776d688f">

should allows finding this problem
<img width="300" alt="Screenshot 2024-01-30 at 13 58 14" src="https://github.com/lemeryfertitta/Climbdex/assets/4202355/6f5ae6a9-5583-4b1a-a01e-09e8e75212e1">

_(really nice work on climbdex !!)_

**Comment by Theruz** [comment]
(I already implemented a proposition, I'll gladly create a PR)

**Comment by lemeryfertitta** [comment]
Absolutely, makes sense. Happy to review your PR, thanks for contributing!

**Comment by lemeryfertitta** [comment]
Deployed - feel free to reopen/create a new issue if anything comes up.
