### ISSUE TITLE
Mirror ticks

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#30]
Similar to the official apps, ticks which have `is_mirror=true` should be indicated differently than ticks with `is_mirror=false`.

The `is_mirror` field is return in the by the [Boardlib `get_logbook`](https://github.com/lemeryfertitta/BoardLib/blob/main/src/boardlib/api/aurora.py#L99) call. In the apps, a backwards checkmark is used to indicate mirror ascent, and the checkmark and backwards checkmark overlapped indicates an ascent of both the mirror and non-mirror of a climb. Something similar could be done for Climbdex, but an SVG will be needed instead of the unicode symbol.

Maybe using https://icons.getbootstrap.com/icons/check/ and then manipulating the SVG as needed for the mirrored/doubled versions.

Example of doubled checkmark:
![Screenshot_20240203-110507](https://github.com/lemeryfertitta/Climbdex/assets/6968022/b2fafaaa-2ea3-4bfe-b8d7-19f266a120a1)

**Comment by abant07** [comment]
Hey could I get started on this one?

**Comment by abant07** [comment]
Hey so I am reproducing the environment, and I just had a question about where I should place the double checkmark, once I figure it out with the SVG manipulation. I checked out the climbdex website that was in the ReadME, and I was wondering if the double checkmark would go next matching climb descriptions after the user filters the climb? I have shown a picture to see if that is the page I should put it on.

<img width="1079" alt="Screenshot 2024-02-04 at 8 39 11 AM" src="https://github.com/lemeryfertitta/Climbdex/assets/100332169/36fcf0e6-26b6-492f-9b2f-a4e3aaf0a0c4">


Thanks

**Comment by lemeryfertitta** [comment]
<img width="1128" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/6968022/ec72782f-150f-44a4-bac4-43145cdd555e">

In this image you can see the checkmark in both the climb list on the left and the climb details on the right. The reverse and doubled checkmarks would go in the same place. So to break down the specific ask a little bit more:

- When a climb with a given UUID appears in the get_logbook results with only is_mirror=false, we display a checkmark similar to what we have now (though for consistency, we should use the SVG instead of the current unicode character).
- When a climb with a given UUID appears in the get_logbook results with only is_mirror=true, we should display a mirrored checkmark (reflected across the y axis)
- When a climb with a given UUID appears in the get_logbook results at least once with is_mirror=false and is_mirror=true, we should display a doubled checkmark (the normal checkmark and mirrored checkmark mashed together, as seen in the picture in the description).

Let me know if you have any other questions!

**Comment by abant07** [comment]
I see, ok thanks for clarifying. 

I had one more questions. I seems I am having having some problem with accessing the sqlite database. I downloaded a database using bin/sync_db.sh <board_name>, however, I still get a sqlite3 error saying its unable to open the database.

**Comment by abant07** [comment]
Actually, I got it, thanks!

**Comment by abant07** [comment]
def get_ticked_climbs(board, login_cookie):
    login_info = flask.json.loads(login_cookie)
    logbook = boardlib.api.aurora.get_logbook(
        board, login_info["token"], login_info["user_id"]
    )
    return [f'{log["climb_uuid"]}-{log["angle"]}' for log in logbook]


is this the method I should be looking at in the views.py file?

**Comment by abant07** [comment]
Also, so you know what filters I can put to see a result with a checkmark, because it seems that I am missing them even though I think I am on the same page as the picture you have above.

<img width="1095" alt="Screenshot 2024-02-04 at 9 17 37 AM" src="https://github.com/lemeryfertitta/Climbdex/assets/100332169/8566da21-4bc5-45b5-9413-2c777d94d7fd">

**Comment by lemeryfertitta** [comment]
> is this the method I should be looking at in the views.py file?

Yes, the `logbook` variable is a list of logbook entries. Each entry should have an `is_mirror` field. 

> it seems that I am missing them even though I think I am on the same page as the picture you have above.

You have to be logged in to the relevant board app and have ticked some climbs on that board. If you haven't climbed on a Kilter (or other) board before and used the official Kilter board app, this may be a bit confusing. If you're curious to learn more, you could [download the app](https://kilterboardapp.com/) and play around with it (e.g. try creating an account and ticking some climbs). This is more of a "good first issue" for someone who has used these apps before. Contributing to this repository will be much more challenging without that background, but you are certainly welcome to if you are still interested.

**Comment by abant07** [comment]
Yeah, Ill give a shot.

**Comment by abant07** [comment]
Ok I was able to solve it, I submitted a PR

Thanks

**Comment by lemeryfertitta** [comment]
Deployed

**Comment by gardaholm** [comment]
very nice addon!
I would only suggest a slightly different svg to make the ticks more obvious. Hard to see the difference for me. 

<img width="1117" alt="old" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/e44fd0e6-8e6d-4a8a-a190-5594f28d3bad">
<img width="1128" alt="new" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/edc01bf8-d151-46cf-a02f-17d5342ff938">
