### ISSUE TITLE
Grade range in one slider

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#40]
Using a [custom slider](https://refreshless.com/nouislider/), we could have grade range in a single input. This is probably more intuitive and also frees up some space on the UI as we can compress one line into two as discussed in #39.

The linked plugin will probably be fairly easy to use, but I'd like to make sure that the style matches well, so it may require some CSS customization to get it looking just right.

**Comment by gardaholm** [comment]
I tried a quick version with the noUIslider, it get's pretty dense due to the 16 Steps. 
and if we want to keep it inline with the other boxes we need to make the slider pretty small. not really happy with this solution, but with some more css modification it may work … 

<img width="511" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/77637a35-df7a-4eaa-93b8-48dc91245523">

**Comment by lemeryfertitta** [comment]
@gardaholm Cool! Couple of ideas:

1. Let's move the slider to be the first filter. I think this is both a good idea in terms of usability (I assume its the most commonly adjusted filter) and in terms of appearance.
2. Could we move the "Grade" label to be floating above or below the slider? Actually, do we even need a label? I feel like it is pretty self explanatory. Ideally we'd keep the font conversion as well, at least until we offer some kind of preferences to show one or the other.
3. If 2 works, we can make the slider the full width of the card (since there is no label). Also, I don't see any issue with increasing the height as well if there are usability issues. Seems okay for it to take up the space of 1.5 or 2 rows of filters if needed (though maybe not necessary)

**Comment by gardaholm** [comment]
true, top position is a good idea and we still would win space by removing the 2 input boxes blow for min and max grades …

<img width="552" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/f0b4c618-6cfe-4f09-9bca-aa09d4bf4631">

**Comment by lemeryfertitta** [comment]
Nice! LGTM
