### ISSUE TITLE
Collapsible advanced filters

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#41]
As discussed in #39, we can free up some space on the filters page by having an "advanced filters" [collapse](https://getbootstrap.com/docs/5.3/components/collapse/).

For now, I'd like to move `Min Rating` and `Grade Accuracy` to this new collapse. Another future candidate for this would be a `Setter` search. This would be a pretty easy add, so we can tack that one onto this issue as well.

**Comment by gardaholm** [comment]
Something like this? 
Tried some toggles or indicators, but somehow the label got either to big (with expand / close icon) or the button/label got too prominent. I would go for the cleaner solution and don't make this label too big or prominent.

<img width="1150" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/917dba21-7355-48e0-bb77-b9a57b3215c0">
