### ISSUE TITLE
Set climbs

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#47]
The `create` page allows for climbs to be illuminated but not saved. After completion of https://github.com/lemeryfertitta/BoardLib/issues/20 they could be uploaded to the Aurora db. There would need to be some UI form for gathering the required fields before uploading.

The create form can be a modal, similar to the login form.

**Comment by ItsDang** [comment]
Will work on this!

**Comment by lemeryfertitta** [comment]
Deployed, thanks @ItsDang !
