### ISSUE TITLE
Use led_color for leds instead of screen_color

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#49]
From #45

**Comment by gardaholm** [comment]
this version is not yet deployed I guess?
had a quick session in the afternoon here and the colors are still off.

**Comment by lemeryfertitta** [comment]
> this version is not yet deployed I guess? had a quick session in the afternoon here and the colors are still off.

Ah yes, forgot to deploy! Going to do a quick PR to remove the arrows then will deploy everything

**Comment by lemeryfertitta** [comment]
@gardaholm LED colors should be deployed now, decided to hold off on arrow removal as I wanted to wrap in a couple of other improvements with that refactor. Let me know if they still seem off.
