### ISSUE TITLE
Uneven icon spacing on climb card

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#54]
<img width="306" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/6968022/23c5cee4-7229-476b-ab37-3bf06fd6f26e">

In addition, I wonder if the arrow icons are even necessary still. With swipe and arrow key support, it seems like the arrow buttons are not even very useful and take up some valuable screen real estate.

**Comment by gardaholm** [comment]
it should be obvious and the space next to the climb_name is already pretty dense, which leads to line-breaks on smaller phones …

**Comment by lemeryfertitta** [comment]
Fix deployed, though we could still consider removing the arrows. Seems fine to leave them for now.
