### ISSUE TITLE
Hold filter enhancement: match all hand types

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#58]
Currently, you can match strict or any, but it is also useful to be able to filter out feet when searching. This could be improved with an "only hands" color match option.

**Comment by ItsDang** [comment]
I want to to give a go, could you clarify what you mean?
- Do you want to remove any feet that have been selected in the filter?
- Or are you saying take all the holds selected and return the climbs that have these holds as hand holds?

**Comment by lemeryfertitta** [comment]
I'm flexible here depending on what folks think is most useful, but my thinking was the "only hands" filter would ignore the color of filter circles and just look for problems with "hands" (aka Start, Finish, or Middle holds) matching the filter. I think this is equivalent to your second interpretation. If someone used this filter and had some footholds selected (i.e. they had filter circles matching the foothold color) those would just be treated as handholds as well.

The idea is that people are usually searching for climbs that use specific hand holds, and it can be annoying if those holds show up as feet in the results problems.

**Comment by lemeryfertitta** [comment]
Deployed! Thanks @ItsDang
