### ISSUE TITLE
Min/max grade set to undefined after returning to filter selection

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#61]
Steps to reproduce:

1. Search for climbs (any filters). 
2. Return to filter selection using the back button or the link
3. Search for climbs again.

The min/max grade are set to "undefined" which causes a 500 error on the search API call.

**Comment by brmnjsh** [comment]
I've resolved this issue, but it appears I don't have the permissions to submit the branch

**Comment by lemeryfertitta** [comment]
Deployed! Thanks @brmnjsh
