### ISSUE TITLE
Show error message on API error

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#62]
The search results page will seem like its loading when the search API has actually returned an error. For example:

https://climbdex.com/results?minGrade=undefined&maxGrade=undefined&name=&angle=any&minAscents=1&sortBy=ascents&sortOrder=desc&minRating=1.0&onlyClassics=0&gradeAccuracy=1&settername=&holds=&mirroredHolds=&board=kilter&layout=1&size=8&set=1&set=20&roleMatch=strict

It would be more useful if there was an error message, possibly with a link to report the issue here.

**Comment by brmnjsh** [comment]
[PR](https://github.com/lemeryfertitta/Climbdex/pull/65) created adding parameter validations as well as toast messages for errors

**Comment by lemeryfertitta** [comment]
@brmnjsh thanks for the PR!

Good question about logging. I hadn't really thought about setting up anything robust yet. I think given the very low number of users currently, I'd just stick with outputting to the console, assuming that's what you mean by local server based. I'm able to get the console output in my fly.io dashboard, so I can generally use that for debugging and such. There are probably a few other features that are higher priority to make Climbdex a better drop-in replacement for the existing apps before more robust logging becomes a priority, but it would eventually be a nice thing to have.

**Comment by brmnjsh** [comment]
@lemeryfertitta alright! I'll log to console for now.

**Comment by lemeryfertitta** [comment]
Deployed! Thanks again, @brmnjsh
