### ISSUE TITLE
Share Climbs

### ISSUE THREAD

**Issue by p4t7m4n** [lemeryfertitta/Climbdex#64]
I looked further into your great project and thought about some improvements. With my basic understanding I could try to implement them but I am not sure if it actually works.

- [ ] It would be great to share climbs to other climbers at the same board (e.g. by adding a button to share the website to friends via NFC). 
- [ ] Also I think it would be nice to enable the functionallity of marking climbs as done.

Do you have anything planned in that direction?

**Comment by lemeryfertitta** [comment]
https://github.com/lemeryfertitta/Climbdex/issues/46 covers marking climbs as done. You're welcome to take a crack at that, I already implemented the API calls in Boardlib but the UI work with Climbdex is still needed.

Sharing climbs more formally would be a nice feature. Maybe we need a separate "climb" page, as the climbs are only displayed as search results at the moment, so the only shareable link right now is a search result.

I've edited the title of this to focus on the sharing aspect as there is already an open issue for marking climbs done.

**Comment by p4t7m4n** [comment]
Thanks for the quick reply. That sounds great! 
If there is anything I could do/code, let me know.

**Comment by lemeryfertitta** [comment]
> Thanks for the quick reply. That sounds great! If there is anything I could do/code, let me know.

You're absolutely welcome to work on any of the open and unassigned issues, including this one or #46 if you are interested. I think #46 is particularly valuable for making Climbdex a drop-in replacement for the existing apps, though it still requires some UI design considerations, which you are also welcome to help out with.

**Comment by lemeryfertitta** [comment]
Going to close this issue, as #46 is complete and there is a new issue for tracking climb sharing with #71
